before_build:
  - nuget restore

# overriding Chrome WebDeriver with v2.10
install:
  - appveyor DownloadFile http://chromedriver.storage.googleapis.com/2.10/chromedriver_win32.zip
  - 7z x chromedriver_win32.zip -y -oC:\Tools\WebDriver

on_finish:
  - ps: Get-ChildItem .\*.png -Recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
